config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :jobs, except: [:edit, :update, :destroy]

  match '/feed' => 'jobs#feed',
        :as => :feed,
        :defaults => { format: 'atom' }, via: :get
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    validates :slug, presence: true, on: :update
    after_save :generate_slug, if: :slug_must_change?

    def to_param
      "#{id}-#{title.parameterize}"
    end
  end

  private

  def slug_must_change?
    slug != to_param
  end

  def generate_slug
    self.slug = to_param
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Sluggable

  validates :title, :description, :email, :company, presence: true
  validates :email, format: { with: /\A[a-z]([\.\-]?\w+)+@[a-z]([\.\-]?\w+){2,}\Z/ }
  validates :website, :url, format: { with: URI.regexp }, allow_blank: true

  default_scope { order(id: :desc) }
  scope :updated_at_desc, -> { order(updated_at: :desc) }

  # enumerator
  enum modality: { modelo: 0, ator: 1, evento: 2, outros: 3 }
  enum salary: { undefined: 0, intern: 1, junior: 2, medium: 3, senior: 4, value_by_hour: 5 }
  enum contract_type: { not_specified: 0, clt: 1, pj: 2 }
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json
  responders :flash

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = JobPresenter.wrap(Job.first(5))
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = JobPresenter.wrap(Job.page(params[:page]).per(4))
    @jobs.where!('modality = ?', Job.modalities[params[:modality]]) unless params[:modality].blank?
    respond_with @jobs
  end

  def new
    @job = Job.new
    respond_with @job
  end

  def create
    @job = Job.new(job_params)
    @job.save
    respond_with @job
  end

  def show
    @job = JobPresenter.new(Job.find(params[:id]))
    respond_with @job
  end

  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = 'Ruby Jobs'

    # the news items
    @job =  Job.updated_at_desc

    # this will be our Feed's update timestamp
    @updated = @job.first.updated_at unless
    @job.empty?

    respond_to do |format|
      format.atom { render layout: false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(format: :atom), status: :moved_permanently }
    end
  end

  private

  def job_params
    params.require(:job).permit(
      :title, :email, :url, :company, :skills, :location, :description,
      :modality, :website, :contract_type, :salary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar(*menus)
    menus.reduce('') { |a, e| a << menu_html(e) }
  end

  def menu_html(value)
    "<li class='#{'active' if current_page?(value[1])}'>
      #{link_to value[0], value[1]}
    </li>"
  end

  def controller_action
    "#{params[:controller]}-#{params[:action]}"
  end

  def markdown(text)
    render_options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow' }
    }
    renderer = Redcarpet::Render::HTML.new(render_options)
    Redcarpet::Markdown.new(renderer).render(text).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def link_to_twitter(title)
    escaped_url = CGI.escape(request.url)
    title       = CGI.escape(title)

    url = 'https://twitter.com/intent/tweet?'
    url += 'hashtags=RubyJobs&'
    url += "original_referer=#{escaped_url}&"
    url += "text=Vaga%20para%20#{title}&"
    url += "w_p=tweetbutton&url=#{escaped_url}"

    render partial: 'jobs/link_to_twitter', locals: { url: url }
  end

  def link_to_linkedin(title)
    escaped_url = CGI.escape(request.url)
    title       = CGI.escape(title)

    url = 'https://www.linkedin.com/shareArticle?mini=true&'
    url += "title=#{title}&"
    url += "url=#{escaped_url}&"
    url += "summary=Vaga%20para%20#{title}&"
    url += 'source=RubyJobs'

    render partial: 'jobs/link_to_linkedin', locals: { url: url }
  end

  def modalities_hash
    { 'Modelo' => :modelo, 'Ator' => :ator, 'Evento' => :evento, 'Outros' => :outros }
  end

  def salaries_hash
    { 'N/A' => :undefined, 'Abaixo de R$300' => :intern, 'R$300 - R$600' => :junior,
      'R$600 - R$900' => :medium, 'Acima de R$1.000' => :senior,
      'Valor hora a combinar' => :value_by_hour  }
  end

  def contract_types_hash
    { 'Não Especificado' => :not_specified, 'CLT' => :clt, 'PJ' => :pj }
  end
end

app/views/home/index.html.erb
<header id="home">
  <div class="container">
<!--     <%= image_tag "logo-with-banner.png", class: "logo" %> -->
    <%= image_tag "logo.jpg", class: "logo" %>
    <h2>Oportunidades para profissionais das Artes e Eventos</h2>
    <p> Anuncie sua vaga no Está Disponível? e deixe mais de 13000 candidados saberem da sua vaga. </p>
    <%= link_to "Anuncie uma vaga!", new_job_path, class: "btn btn-ghost"%>
  </div>
</header>


<div class="main-section" id="<%= controller_action %>">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="page-header">
          <h1>Vagas recentes</h1>
        </div>
        <table class="jobs-list">
          <% @jobs.each do |job| %>
            <tr class="<%= job.modality %>">
              <%= content_tag :td, image_tag(job.badge), class: "job-badge" %>
              <%= content_tag :td, class: "job-title-company" do %>
                <%= content_tag :p, (link_to (truncate(job.title, :length => 50)), job_path(job)), class: "job-title" %>
                <%= content_tag :p, (truncate(job.company, :length => 40)), class: "job-company" %>
              <% end %>
              <%= content_tag :td, (truncate(job.location, :length => 28)), class: "job-location" %>
              <td class="job-date badger-right badger-<%= job.modality %>" data-badger="<%= job.modality_name %>">
                <%= job.created_at.strftime("%d/%m/%Y") %>
              </td>
            </tr>
          <% end %>
        </table>
        <%= link_to "Ver + vagas", :jobs, class: "show-more-jobs" %>
      </div>
    </div>
    <!--<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
      style="display:inline-block;width:728px;height:90px"
      data-ad-client="ca-pub-3241477158749799"
      data-ad-slot="6093586062"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>-->

  </div>
</div>

app/views/jobs/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <%= simple_form_for @job, wrapper_mappings: { radio_buttons: :vertical_radio_and_checkboxes } do |f| %>
      <%= f.error_notification %>
      <h3>Dados da Agência / Produtor</h3>
      <%= f.input :company %>
      <%= f.input :website, as: :url %>
      <%= f.input :email %>
      <%= f.input :url, as: :url %>
      <h3>Dados da vaga</h3>
      <%= f.input :title %>
      <%= f.input :modality, as: :radio_buttons, collection: modalities_hash %>
      <%= f.input :location %>
      <%= f.input :description%>
<!--       <%= f.input :skills %> -->
<!--       <%= f.input :contract_type, as: :radio_buttons, collection: contract_types_hash %> -->
      <%= f.input :salary, as: :radio_buttons, collection: salaries_hash %>
      <!--
      <%= f.label :description %>
      <div id="description-editor" class="markdown-editor">
        <ul class="nav nav-tabs" data-tabs="tabs">
          <li class="active">
            <a href="#text" data-toggle="tab">Markdown</a>
          </li>
          <li>
            <a href="#preview" data-toggle="tab">Preview</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="text">
            <%= f.input :description, input_html: { :size => '50x5', 'v-model' => 'description' }, label: false %>
          </div>
          <div class="tab-pane" id="preview">
            <div class="preview" v-html="description | marked"></div>
          </div>
        </div>
      </div>
      -->

      <%= link_to 'Voltar', root_url, :class => 'btn btn-default' %>
      <%= f.button :submit, label: "Salvar", class: "btn btn-brand" %>
    <% end %>
  </div>
</div>

app/views/jobs/_link_to_linkedin.html.erb
<%= link_to url, class: 'btn btn-primary', target: :blank do %>
  <i class="fa fa-linkedin fa-lg"> </i>
<% end %>

app/views/jobs/_link_to_twitter.html.erb
<%= link_to url, class: 'btn btn-info', target: :blank do %>
  <i class="fa fa-twitter fa-lg"></i>
<% end %>

app/views/jobs/index.html.erb
<header id="inner">
  <div class="container">
  </div>
</header>

<div class="main-section" id="<%= controller_action %>" ng-controller="JobsCtrl">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="page-header">
          <h1>Confira nossas vagas! Merda pra Nós! </h1>
        </div>

        <input type="text" placeholder="Que tipo de Job você esta procurando?" ng-model="search" class="form-control"><br/>

        <table class="jobs-list">
          <tbody infinite-scroll="loadMore()" infinite-scroll-distance="3">
            <tr class="{{::job.modality}}" ng-repeat="job in jobs | filter:search">
              <td class="job-badge"><img ng-src="{{::job.badge}}"></td>
              <td class="job-title"><a ng-href="{{::job.url}}">{{::job.title}}</a></td>
              <td class="job-company">
                <a ng-href="{{::job.website}}" ng-if="job.website">
                  {{::job.company}}
                </a>
                <span ng-if="!job.website">
                  {{::job.company}}
                </span>
              </td>
              <td class="job-location"> {{::job.location}} </td>
              <td class="job-date badger-right badger-{{::job.modality}}" data-badger="{{job.modality_name}}">
                {{job.posted_at | date}}

              </td>
            </tr>
          </tbody>
        </table>

        <div class="spinner" ng-show="loading">
          <div class="rect1"></div>
          <div class="rect2"></div>
          <div class="rect3"></div>
          <div class="rect4"></div>
          <div class="rect5"></div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/jobs/new.html.erb
<header id="inner">
</header>

<div class="main-section" id="<%= controller_action %>">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="page-header">
          <h1>Cadastrar Novo Job</h1>
        </div>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<% content_for :opengraph do %>
  <meta property="og:type" content="article">
  <%= tag("meta", property: "og:title", content: @job.title ) %>
  <%= tag("meta", property: "og:description", content: @job.description ) %>
  <%= tag("meta", property: "og:url", content: job_url(@job) ) %>
  <%= tag("meta", property: "og:image", content: asset_url('logo-for-opengraph.png') ) %>
  <%= tag("meta", property: "og:site_name", content: "Ruby Jobs" ) %>
<% end %>

<header id="inner">
  <div class="container">
  </div>
</header>

<div class="main-section">
  <div class="container">

    <div class="page-header">
      <%= content_tag :div, class: "alert alert-success fade in" do %>
        <%= content_tag :button, 'X', class: "close", data: { dismiss: "alert"  } %>
        <%= flash[:notice] %>
      <% end if flash[:notice] %>

      <h1>
        <%= @job.title %>
      </h1>
      <p>
        <%= content_tag :span, class: "job-company" do %>
          <%= link_to_unless @job.website.blank?, @job.company, @job.website %>
        <% end %>
        <%= content_tag :span, "#{@job.location}/#{@job.modality_name}", class: "job-location" %>
        <%= content_tag :span, "Vaga criada em: " + l(@job.created_at, format: :long), class: "job-date" %>
<!--         <%= content_tag :span, %(Contratação: #{@job.contract_type_label}), format: :long,
          class: "job-contract-type-#{@job.contract_type}" %> -->

      </p>
    </div>

    <div class="job-description">
      <h4> Descrição </h4>
      <%= markdown @job.description %>
    </div>

    <%= content_tag :div, class: "well skills" do %>
      <h4> Habilidades </h4>
      <%= @job.skills %>
    <% end if @job.skills.present? %>

    <%= content_tag :span, %(Salário: #{@job.salary_label}), format: :long, class: "job-salary-#{@job.salary}" %>

    <div class="row do-you-like-it">

      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
        <%= image_tag  "logo.jpg" %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <h4> Está Disponível? </h4>
        <p>
          <% if @job.url.present? %>
            <%= link_to 'Participe do processo de seleção, clique no link: ', @job.url %> e caso seja contratado deixe-nos saber!
          <% else %>
            Entre em contato com o responsável pelo email <%= content_tag :span, @job.email, class: "email" %> e caso seja contratado deixe-nos saber!
          <% end %>
        </p>
      </div>

    </div>

    <%= link_to 'Voltar', root_url, :class => 'btn btn-default' %>
    <%= link_to_twitter @job.title %>
    <%= link_to_linkedin @job.title %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p> Copyright © <%= Time.now.year %> <strong>EstaDisponível.com</strong> </p>
      <div class="links">
<!--         <%= link_to image_tag("rss_icon.png"), feed_path %>
        <%= link_to image_tag("github.png"), "https://github.com/ruby-jobs/ruby-jobs" %> -->
      </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="main-nav" class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to (image_tag "logo.jpg"), root_path, class: 'navbar-brand' %>
    </div>

    <div id="site-nav" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
       <%= navbar(
        ['Vagas', jobs_path],
        ['Anuncie', new_job_path]
        ).html_safe %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="rubyJobs">
<head>
  <title>Está Disponível? | Vagas para Artistas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>

  <%= favicon_link_tag 'ruby.png' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= yield :opengraph %>

</head>
<body id="<%= controller_action %>">
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>
</html>